[package]
name = "glium_derive"
version = "0.1.0"
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]
description = "Custom derive for glium Vertex"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "0.14.2"
quote = "0.6.3"
synstructure = "0.9.0"
