name: ci

on: [push, pull_request]

env:
  RUSTFLAGS: -D warnings

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Run cargo check
      run: |
        cargo check --all
    - name: Compile the tests
      run: |
         cargo test --all --all-targets --no-run
    - name: Run cargo doc
      run: |
        cargo doc --all --all-features
